_wandb:
    value:
        cli_version: 0.24.2
        e:
            cteppqjx796fldabj9dc3crlsis1fym0:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 19262f407a49ad4b49543d15169bac8ec139e0e7
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h185
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                startedAt: "2026-02-23T14:49:45.722851Z"
                writerId: cteppqjx796fldabj9dc3crlsis1fym0
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 3
                - 13
                - 16
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 600
H:
    value: 200
LOG_EVERY:
    value: 1000
M_target:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
MAX_ITER:
    value: 1000000000
"N":
    value: 1002
THRESHOLD:
    value: 1e-21
chi_init:
    value:
        - - 1
          - 0
          - 0
        - - 0
          - 0
          - 0
        - - 0
          - 0
          - 0
damping:
    value: 0.01
initialization_chi:
    value: one_hot
loss_mu:
    value: soft_l1
mu0:
    value:
        - 0
        - 0
        - 0
seed:
    value: 951520
settingmu:
    value: previous
