_wandb:
    value:
        cli_version: 0.24.2
        e:
            veu4ebmhguqw4zdhxb46mfkw55hqjunt:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                cpu_count: 36
                cpu_count_logical: 36
                disk:
                    /:
                        total: "53660876800"
                        used: "6781112320"
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 6dd735c1b613d7b7f86f23f81a5af7cfbdd84147
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h125
                memory:
                    total: "201911074816"
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                slurm:
                    cluster_name: helvetios
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000FF
                    cpu_bind_list: "0x0000000FF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: cyclic
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "8"
                    job_end_time: "1770986457"
                    job_gid: "30124"
                    job_id: "6786312"
                    job_name: bp_test_run
                    job_nodelist: h125
                    job_num_nodes: "1"
                    job_partition: standard
                    job_qos: serial
                    job_start_time: "1770900057"
                    job_uid: "309744"
                    job_user: busato
                    jobid: "6786312"
                    launch_node_ipaddr: 10.91.19.125
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: h125
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.91.19.125
                    srun_comm_port: "38581"
                    step_id: "0"
                    step_launcher_port: "38581"
                    step_nodelist: h125
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/busato/assortative_partitions
                    submit_host: helvetios2
                    task_pid: "3699166"
                    tasks_per_node: "1"
                    topology_addr: t1.h6.h125
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu:8
                    umask: "0022"
                startedAt: "2026-02-12T12:41:03.132624Z"
                writerId: veu4ebmhguqw4zdhxb46mfkw55hqjunt
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 9
H:
    value: 3
LOG_EVERY:
    value: 1000
M_target:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
MAX_ITER:
    value: 2500000
"N":
    value: 16
THRESHOLD:
    value: 1e-10
chi_init:
    value:
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
damping:
    value: 0.005
loss_mu:
    value: soft_l1
mu0:
    value:
        - 0
        - 0
        - 0
seed:
    value: 941676
settingmu:
    value: always_zero
