_wandb:
    value:
        cli_version: 0.24.2
        e:
            3uqiyu1pzzop1skb4vc12no9a7hoc8lw:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 9e1cf2ee7751c27f55d3bbd2d2fdb47722e720a7
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h121
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                startedAt: "2026-02-13T12:28:31.964954Z"
                writerId: 3uqiyu1pzzop1skb4vc12no9a7hoc8lw
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 15
H:
    value: 5
LOG_EVERY:
    value: 1000
M_target:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
MAX_ITER:
    value: 10000000
"N":
    value: 18
THRESHOLD:
    value: 1e-11
chi_init:
    value:
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
damping:
    value: 1
loss_mu:
    value: soft_l1
mu0:
    value:
        - 0
        - 0
        - 0
seed:
    value: 662783
settingmu:
    value: previous_mu
