_wandb:
    value:
        cli_version: 0.24.2
        e:
            4ue8y1nhq5nr35rwjzz75a0x7omuoazp:
                codePath: hardcoded_solver_3_assortative.py
                codePathLocal: hardcoded_solver_3_assortative.py
                cpu_count: 36
                cpu_count_logical: 36
                disk:
                    /:
                        total: "53660876800"
                        used: "6972985344"
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 81abf1479a5eb328cf3dabf96e4871d2832e4ca3
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h121
                memory:
                    total: "201911074816"
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/hardcoded_solver_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                slurm:
                    cluster_name: helvetios
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x003FC0000
                    cpu_bind_list: "0x003FC0000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: cyclic
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "8"
                    job_end_time: "1770913795"
                    job_gid: "30124"
                    job_id: "6786283"
                    job_name: hardcoded_test_run
                    job_nodelist: h121
                    job_num_nodes: "1"
                    job_partition: standard
                    job_qos: serial
                    job_start_time: "1770827395"
                    job_uid: "309744"
                    job_user: busato
                    jobid: "6786283"
                    launch_node_ipaddr: 10.91.19.121
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: h121
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.91.19.121
                    srun_comm_port: "36033"
                    step_id: "0"
                    step_launcher_port: "36033"
                    step_nodelist: h121
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/busato/assortative_partitions
                    submit_host: helvetios2
                    task_pid: "2267034"
                    tasks_per_node: "1"
                    topology_addr: t1.h6.h121
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu:8
                    umask: "0022"
                startedAt: "2026-02-11T16:29:59.636688Z"
                writerId: 4ue8y1nhq5nr35rwjzz75a0x7omuoazp
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 8
H:
    value: 4
M:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
"N":
    value: 15
