_wandb:
    value:
        cli_version: 0.24.2
        e:
            w49r222x903ti3zvmi3kmazdeb4zcaqb:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                cpu_count: 36
                cpu_count_logical: 36
                disk:
                    /:
                        total: "53660876800"
                        used: "5870743552"
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 4f365d28dc38d971782a8fc1702c7a177e618b6b
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h190
                memory:
                    total: "201911078912"
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                slurm:
                    cluster_name: helvetios
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00FF00000
                    cpu_bind_list: "0x00FF00000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: cyclic
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "8"
                    job_end_time: "1771930280"
                    job_gid: "30204"
                    job_id: "6821594"
                    job_name: bp_test_run
                    job_nodelist: h190
                    job_num_nodes: "1"
                    job_partition: standard
                    job_qos: serial
                    job_start_time: "1771843880"
                    job_uid: "309744"
                    job_user: busato
                    jobid: "6821594"
                    launch_node_ipaddr: 10.91.19.190
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: h190
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.91.19.190
                    srun_comm_port: "35619"
                    step_id: "0"
                    step_launcher_port: "35619"
                    step_nodelist: h190
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/busato/assortative_partitions
                    submit_host: helvetios2
                    task_pid: "975846"
                    tasks_per_node: "1"
                    topology_addr: t1.h8.h190
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu:8
                    umask: "0022"
                startedAt: "2026-02-23T10:51:23.748949Z"
                writerId: w49r222x903ti3zvmi3kmazdeb4zcaqb
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 600
H:
    value: 200
LOG_EVERY:
    value: 1000
M_target:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
MAX_ITER:
    value: 1000000000
"N":
    value: 1002
THRESHOLD:
    value: 1e-21
chi_init:
    value:
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
        - - 0.1111111111111111
          - 0.1111111111111111
          - 0.1111111111111111
damping:
    value: 0.01
loss_mu:
    value: soft_l1
mu0:
    value:
        - 0
        - 0
        - 0
seed:
    value: 397036
settingmu:
    value: always_zero
