_wandb:
    value:
        cli_version: 0.24.2
        e:
            p8plfvhshisb8ujngoskduivqxy572cv:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                cpu_count: 36
                cpu_count_logical: 36
                disk:
                    /:
                        total: "53660876800"
                        used: "5902475264"
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: 19262f407a49ad4b49543d15169bac8ec139e0e7
                    remote: https://github.com/matteabusato/assortative_partitions.git
                host: h185
                memory:
                    total: "201911078912"
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                slurm:
                    cluster_name: helvetios
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0xFF0000000
                    cpu_bind_list: "0xFF0000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: cyclic
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "8"
                    job_end_time: "1771944945"
                    job_gid: "30204"
                    job_id: "6821799"
                    job_name: bp_test_run
                    job_nodelist: h185
                    job_num_nodes: "1"
                    job_partition: standard
                    job_qos: serial
                    job_start_time: "1771858545"
                    job_uid: "309744"
                    job_user: busato
                    jobid: "6821799"
                    launch_node_ipaddr: 10.91.19.185
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: h185
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.91.19.185
                    srun_comm_port: "46603"
                    step_id: "0"
                    step_launcher_port: "46603"
                    step_nodelist: h185
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/busato/assortative_partitions
                    submit_host: helvetios2
                    task_pid: "528361"
                    tasks_per_node: "1"
                    topology_addr: t1.h8.h185
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu:8
                    umask: "0022"
                startedAt: "2026-02-23T14:55:48.821862Z"
                writerId: p8plfvhshisb8ujngoskduivqxy572cv
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 600
H:
    value: 200
LOG_EVERY:
    value: 1000
M_target:
    value:
        - 0.3333333333333333
        - 0.3333333333333333
        - 0.3333333333333333
MAX_ITER:
    value: 1000000000
"N":
    value: 1002
THRESHOLD:
    value: 1e-21
chi_init:
    value:
        - - 0.17391622155282696
          - 0.16445149061672798
          - 0.157203191978507
        - - 0.008062738916827019
          - 0.12920147924010145
          - 0.19591526238224982
        - - 0.03896857593005552
          - 0.08064133340255775
          - 0.051639705980146444
damping:
    value: 0.01
initialization_chi:
    value: gaussian
loss_mu:
    value: soft_l1
mu0:
    value:
        - 0
        - 0
        - 0
seed:
    value: 232738
settingmu:
    value: always_zero
